services:
  keydb:
    image: eqalpha/keydb
    hostname: keydb
    volumes:
      - "/meower-data/env/keydb.conf:/etc/keydb/keydb.conf"
      - "/meower-data/logs/keydb:/etc/keydb/logs"
    networks:
      - meower_keydb
    ports:
      - target: 6379
        published: 6379
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first

networks:
  meower_keydb:
    external: true