services:
  keydb:
    image: eqalpha/keydb
    volumes:
      - "/meower-data/keydb/keydb.conf:/etc/keydb/keydb.conf"
      - "/meower-data/keydb/logs:/etc/keydb/logs"
      - "/meower-data/keydb/dump.rdb:/data/dump.rdb"
    networks:
      - host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first

networks:
  host:
    name: host
    external: true