services:
  s3:
    image: minio/minio
    command: >
      sh -c "
        minio server /data --address :8000 &
        minio server /data --address :9000 --console-address ":9001" --cert /etc/minio.crt --key /etc/minio.key
      "
    command: server /data 
    env_file: /meower-data/s3/.env
    volumes:
      - /meower-data/s3/data:/data
      - /meower-data/certs/minio.crt:/etc/minio.crt:ro
      - /meower-data/certs/minio.key:/etc/minio.key:ro
    ports:
      - target: 8000
        published: 8000
        mode: host
      - target: 9000
        published: 9000
        mode: host
      - target: 9001
        published: 9001
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.s3 == yes
