services:
  postgres:
    image: postgres
    env_file: /meower-data/postgres/data.env
    volumes:
      - /meower-data/postgres/data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.zone == us_east_1