services:
    registry:
        image: registry:2
        environment:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
            - /mnt/meower/registry:/data
        ports:
            - "5000:5000"
