services:
    registry:
        image: registry:2
        ports:
            - "5000:5000"
        environment:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
            - /mnt/meower/registry:/data
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.zone == mike
