services:
  us_east_1:
    image: minio/minio
    hostname: s3_us_east_1
    command: server /data --console-address ":9001"
    env_file: /meower-data/env/s3.env
    volumes:
      - /meower-data/s3:/data
    networks:
      - meower_uploads
    ports:
      - target: 9000
        published: 9000
        mode: host
      - target: 9001
        published: 9001
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.zone == us_east_1
  us_west_1:
    image: minio/minio
    hostname: s3_us_west_1
    command: server /data --console-address ":9001"
    env_file: /meower-data/env/s3.env
    volumes:
      - /meower-data/s3:/data
    networks:
      - meower_uploads
    ports:
      - target: 9000
        published: 9000
        mode: host
      - target: 9001
        published: 9001
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.zone == us_west_1

networks:
  meower_uploads:
    external: true