services:
  app:
    image: 100.80.1.1:5000/uploads:1.0.0
    hostname: uploads
    env_file: /meower-data/env/uploads.env
    networks:
      - meower_uploads
    ports:
      - target: 5500
        published: 5500
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.uploads == yes

  cf:
    image: cloudflare/cloudflared
    command: tunnel run
    env_file: /meower-data/env/uploads_cf.env
    networks:
      - meower_uploads
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.uploads == yes

networks:
  meower_uploads:
    external: true