services:
  us_east:
    image: 100.80.1.1:5000/uploads:1.5.0
    hostname: uploads
    volumes:
      - /meower-data/uploads/.env:/app/.env:ro
    networks:
      - us_east_uploads
    ports:
      - target: 5500
        published: 5500
        mode: host
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.region == us_east
          - node.labels.uploads == yes
        preferences:
          - spread: node.labels.zone

  us_east_cf:
    image: cloudflare/cloudflared
    command: tunnel run
    env_file: /meower-data/uploads/cf.env
    networks:
      - us_east_uploads
    depends_on:
      - us_east
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.region == us_east
          - node.labels.uploads == yes
        preferences:
          - spread: node.labels.zone

  us_west:
    image: 100.80.1.1:5000/uploads:1.5.0
    hostname: uploads
    volumes:
      - /meower-data/uploads/.env:/app/.env:ro
    networks:
      - us_west_uploads
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.region == us_west
          - node.labels.uploads == yes
        preferences:
          - spread: node.labels.zone

  us_west_cf:
    image: cloudflare/cloudflared
    command: tunnel run
    env_file: /meower-data/uploads/cf.env
    networks:
      - us_west_uploads
    depends_on:
      - us_west
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.region == us_west
          - node.labels.uploads == yes
        preferences:
          - spread: node.labels.zone

networks:
  us_east_uploads:
    driver: overlay
    attachable: true
  us_west_uploads:
    driver: overlay
    attachable: true
